version: '3'

services:
  app:
    build: .
    environment:
      - POSTGRES_NAME_NETFLIX=netflix_2
      - POSTGRES_USER=learn
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres
    environment:
      - POSTGRES_NAME=netflix_2
      - POSTGRES_USER=learn
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data

