name: Movie API CD

on:
  push:
    branches: [master]


jobs:
  run-tests:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_NAME_NETFLIX: netflix_2
          POSTGRES_USER: learn
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest 
    
  deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 159.89.104.118
          username: root
          key: ${{ secrets.KEY }}
          script: |
            cd netflixapi
            git pull
            systemctl restart gunicorn.service
